### ISSUE TITLE
Remove controller logic from index.html

### ISSUE THREAD

**Issue by dmchaleATarinc** [addevonly/workshop1-angular-intro#2]

**Comment by cmercerATarinc** [comment]
nice

**Comment by mdiaATarinc** [comment]
First issue. yay!

**Comment by qyaoATArinc** [comment]
cool

**Comment by jbisaskyATarinc** [comment]
Closed the issue from the commit message!

**Comment by jbisaskyATarinc** [comment]
syntax: git commit -m "blah blah closes #[issue number]" [files]

**Comment by jbisaskyATarinc** [comment]
Added 'use strict' to top of function according to Mohit's review comment. Closing now.
